# Generated by Django 5.0.1 on 2025-11-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='budgetManager.months'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='finYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finIds', to='budgetManager.financialyear'),
        ),
    ]
