# Generated by Django 5.0.1 on 2025-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0002_sheet_month_alter_sheet_finyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
