# Generated by Django 5.0.1 on 2025-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0003_cell_formula_alter_cell_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, null=True)),
                ('isExpensive', models.BooleanField(default=False)),
            ],
        ),
    ]
