# Generated by Django 5.0.1 on 2025-11-05 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0004_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedOn', models.DateField(null=True)),
                ('amount', models.PositiveIntegerField()),
                ('finYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finyrs', to='budgetManager.financialyear')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgetManager.items')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthids', to='budgetManager.months')),
            ],
        ),
    ]
