# Generated by Django 5.0.1 on 2025-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0006_monthlydata_valuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='valueType',
            field=models.CharField(choices=[('ET', 'Expected Total'), ('MD', 'Monthly Data'), ('NIC', 'NIC'), ('PR', 'Prathibha')], default='MD', max_length=10, null=True),
        ),
    ]
