# Generated by Django 5.0.1 on 2025-11-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0007_alter_monthlydata_valuetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtGivenDate', models.DateField(null=True)),
                ('debtGivenTo', models.CharField(max_length=100, null=True)),
                ('debtGivenAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('debtPaidDate', models.DateField(null=True)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanTakenDate', models.DateField(null=True)),
                ('loanTakenFrom', models.CharField(max_length=100, null=True)),
                ('loanAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loanInterest', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('loanAmountPaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('loanPaidDate', models.DateField(null=True)),
                ('isClosed', models.BooleanField(default=False)),
            ],
        ),
    ]
