# Generated by Django 5.0.1 on 2025-11-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0008_debtmanager_loanmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtmanager',
            name='debtPaidDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
