# Generated by Django 5.0.1 on 2025-11-14 04:09

from django.db import migrations

def add_months(apps, schema_editor):
    Months = apps.get_model('budgetManager', 'Months')
    data = [
        ("January", "Jan"),
        ("February", "Feb"),
        ("March", "Mar"),
        ("April", "Apr"),
        ("May", "May"),
        ("June", "Jun"),
        ("July", "Jul"),
        ("August", "Aug"),
        ("September", "Sep"),
        ("October", "Oct"),
        ("November", "Nov"),
        ("December", "Dec"),
    ]
    for desc, abbr in data:
        Months.objects.create(monthDesc=desc, monthAbbr=abbr)

def remove_months(apps, schema_editor):
    Months = apps.get_model('budgetManager', 'Months')
    Months.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0009_alter_debtmanager_debtpaiddate'),
    ]

    operations = [
        migrations.RunPython(add_months, reverse_code=remove_months),
    ]

