# Generated by Django 5.0.1 on 2025-11-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0010_auto_20251114_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payedOn', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loanName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanName', to='budgetManager.loanmanager')),
            ],
        ),
    ]
