# Generated by Django 5.0.1 on 2025-12-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetManager', '0011_loantrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
