# Generated by Django 5.0.1 on 2025-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='mfNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfName', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mf_names',
            },
        ),
    ]
