# Generated by Django 5.0.1 on 2025-11-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20251107_1022'),
    ]

    operations = [
    ]
