# Generated by Django 5.0.1 on 2025-11-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20251107_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holiday',
            field=models.DateField(),
        ),
    ]
