# Generated by Django 5.0.1 on 2025-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_holidays_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknames',
            name='strongUpdatedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
