# Generated by Django 5.0.1 on 2025-11-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_stocknames_strongupdatedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcodes',
            name='lastFetchedOn',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
