# Generated by Django 5.0.1 on 2025-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_stockcodes_lastfetchedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcodes',
            name='lastFetchedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
