# Generated by Django 5.0.1 on 2025-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_stockcodes_lastfetchedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknames',
            name='sectorUpdatedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprofitratios',
            name='updatedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendysector',
            name='updatedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
