# Generated by Django 5.0.1 on 2025-11-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_stocknames_sectorupdatedon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longstocks',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='MultibaggerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('fundamentals', models.FloatField(default=0)),
                ('technicals', models.FloatField(default=0)),
                ('momentum', models.FloatField(default=0)),
                ('promoter', models.FloatField(default=0)),
                ('sector', models.FloatField(default=0)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mb_score', to='api.stocknames')),
            ],
        ),
    ]
