# Generated by Django 5.0.1 on 2025-11-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_longstocks_score_multibaggerscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='longstocks',
            name='recommendation',
            field=models.CharField(default='Hold', max_length=20),
        ),
    ]
