# Generated by Django 5.0.1 on 2025-11-07 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20251107_0535'),
        ('budgetManager', '0009_alter_debtmanager_debtpaiddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transDate', models.DateField(null=True)),
                ('transValue', models.TextField(blank=True, null=True)),
                ('transType', models.CharField(blank=True, choices=[('INTRA', 'Intra day trading'), ('MTFT', 'Margin Trading Fund'), ('SWING', 'Swing Trading'), ('LONG', 'Long Posintion')], max_length=15, null=True)),
                ('finYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transYr', to='budgetManager.financialyear')),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transHead', to='assets.stockheadings')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transMnth', to='budgetManager.months')),
            ],
        ),
    ]
