# Generated by Django 5.0.1 on 2025-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_stocktransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='transType',
            field=models.CharField(blank=True, choices=[('INTRA', 'Intra day trading'), ('MTFT', 'Margin Trading Fund'), ('SWING', 'Swing Trading'), ('LONG', 'Long Posintion'), ('OPTION', 'OPtion trading data')], max_length=15, null=True),
        ),
    ]
