# Generated by Django 5.0.1 on 2025-11-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_stocktransactions_transtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactions',
            name='refNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransactions',
            name='slNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
