# Generated by Django 5.0.1 on 2025-11-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_stocktransactions_refno_stocktransactions_slno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransactions',
            name='transDate',
        ),
    ]
