# Generated by Django 5.0.1 on 2025-11-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20251107_1023'),
        ('assets', '0007_remove_stocktransactions_transdate'),
        ('budgetManager', '0009_alter_debtmanager_debtpaiddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedOn', models.DateField(blank=True, null=True)),
                ('sellOn', models.DateField(blank=True, null=True)),
                ('purchasedAmnt', models.IntegerField(blank=True, null=True)),
                ('purchasedQty', models.PositiveIntegerField(blank=True, null=True)),
                ('sellAmnt', models.IntegerField(blank=True, null=True)),
                ('sellQty', models.PositiveIntegerField(blank=True, null=True)),
                ('buyBrock', models.IntegerField(blank=True, null=True)),
                ('sellBrock', models.IntegerField(blank=True, null=True)),
                ('totalTax', models.IntegerField(blank=True, null=True)),
                ('totalPurchasedAmnt', models.IntegerField(blank=True, null=True)),
                ('totalSellAmnt', models.IntegerField(blank=True, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('finYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stkYr', to='budgetManager.financialyear')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stkMnth', to='budgetManager.months')),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stkName', to='api.stocknames')),
            ],
        ),
    ]
