# Generated by Django 5.0.1 on 2025-11-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_stockdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactions',
            name='isProcessed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
