# Generated by Django 5.0.1 on 2025-11-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_stocktransactions_isprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='refNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
