# Generated by Django 5.0.1 on 2025-11-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_stockdetails_refno'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='transType',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
