# Generated by Django 5.0.1 on 2025-11-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_stockdetails_transtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='finYear',
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='month',
        ),
    ]
