# Generated by Django 5.0.1 on 2025-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_remove_stockdetails_finyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='totalTax',
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='purchasedReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='sellReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
