# Generated by Django 5.0.1 on 2025-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_stockdetails_totaltax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdetails',
            old_name='remarks',
            new_name='buyRemarks',
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='sellRemarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
