# Generated by Django 5.0.1 on 2025-11-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_rename_remarks_stockdetails_buyremarks_and_more'),
        ('budgetManager', '0009_alter_debtmanager_debtpaiddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='buyFinYear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyYr', to='budgetManager.financialyear'),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='sellFinYear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellYr', to='budgetManager.financialyear'),
        ),
    ]
