# Generated by Django 5.0.1 on 2025-11-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20251107_1023'),
        ('assets', '0015_stockdetails_buyfinyear_stockdetails_sellfinyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='optionName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='stock',
            field=models.ForeignKey(blank=True, db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stkName', to='api.stocknames'),
        ),
    ]
