# Generated by Django 5.0.1 on 2025-11-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20251107_1023'),
        ('assets', '0016_stockdetails_optionname_alter_stockdetails_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='mfName',
            field=models.ForeignKey(blank=True, db_column='mf_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutualfundName', to='api.mfnames'),
        ),
    ]
