# Generated by Django 5.0.1 on 2025-11-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_holidays_holiday'),
        ('assets', '0017_stockdetails_mfname'),
        ('budgetManager', '0010_auto_20251114_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='buyBrock',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='purchasedAmnt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='purchasedQty',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='refNo',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='sellAmnt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='sellBrock',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='sellQty',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='totalPurchasedAmnt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='totalSellAmnt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='dividentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divDate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('finYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divYr', to='budgetManager.financialyear')),
                ('stock', models.ForeignKey(blank=True, db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divStkName', to='api.stocknames')),
            ],
        ),
    ]
